name: marp-to-pages
concurrency: marp-to-pages

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup Python3
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version: "3.x"
      
      - name: Install ImageMagick
        uses: mfinelli/setup-imagemagick@e5a049b136cb833d5c0474b38d166f0bdb0e4497 #v7.0.1
        with:
          cache: true

      - name: Ensure build dir exists
        run: |
          mkdir -p build

      - name: Fetch Freud Style CSS
        run: |
          curl -sL https://cunhapaulo.github.io/style/freud.css -o build/freud.css

      - name: Copy images directory (if exists)
        run: |
          cp -R img build/img

      - name: Marp Build (slides.md)
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          args: slides.md -o build/index.html
        env:
          MARP_USER: root:root

      - name: Marp Build (slides.pdf)
        uses: docker://marpteam/marp-cli:v4.2.3
        with:
          args: slides.md --allow-local-files -o build/slides.pdf
        env:
          MARP_USER: root:root

      - name: Optimise PDF size
        run: |
          gs -sDEVICE=pdfwrite \
          -dCompatibilityLevel=1.4 \
          -dPDFSETTINGS=/default \
          -dDetectDuplicateImages \
          -dCompressFonts=true \
          -r150 \
          -o build/slides-optimized.pdf \
          build/slides.pdf
          rm build/slides.pdf

      # - name: Marp Build (slides.pptx)
      #   uses: docker://marpteam/marp-cli:v3.4.0
      #   with:
      #     args: slides.md --allow-local-files -o build/slides.pptx
      #   env:
      #     MARP_USER: root:root

      # - name: Optimise PPTX size
      #   run: |
      #     compress-pptx build/slides.pptx

      - name: Deploy preview
        if: ${{ github.event_name == 'pull_request' }}
        uses: rossjrw/pr-preview-action@9f77b1d057b494e662c50b8ca40ecc63f21e0887 # v1.6.2
        with:
          source-dir: ./build/
          preview-branch: gh-pages
          umbrella-dir: pr-preview

      - name: Deploy production
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          branch: gh-pages
          folder: ./build/
          clean-exclude: pr-preview/

